name: Validate Packer 

on:
  	pull_request:
      types: [completed]
    	branches: [ "main" ]

jobs:
	packer:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout repo
			  uses: actions/checkout@v2
      
      - name: Packer build
				run: packer build -on-error=abort ./ami/aws.pkr.hcl
